name: Check Pull Request Title
on:
    pull_request:
        types: [opened, synchronize, edited]

jobs:
    check-pull-request-title:
        name: Check Pull Request Title
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Lint Pull Request
              uses: Eu4ng/action-lint-pull-request@main