name: Lint Commit
on:
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    lint-commit:
        name: Lint Commit
        runs-on: ubuntu-latest
        steps:
            - name: Check Out
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Check Commit Messages
              uses: wagoid/commitlint-github-action@v5